### PR TITLE
#13: Add Inversion support for DAGify method

### PR DESCRIPTION
**Pull request by 6br**
This pull request is successor of #9, and I modified the original implementation to support inversion.

1. Inverted nodes are aligned the same slice.
2. Slice has "NodeTraversal" to store the strand of node.

### CODE REVIEW

**Comment by 6br** [comment]
Inversion in DAGify have many breaking change on `graph.py` to support inversion (i.e. "-" strand on slices). If you don't prefer these changes, then please add comments.

**Comment by josiahseaman** [comment]
@6br Did you still want this merged with master or is the work not done yet?  I noticed it currently has conflicts.  I apologize if I'm the one that created those conflicts with master.

**Comment by 6br** [comment]
I will fix the conflicts. I think I have done my implementation, but is it okay if Slice has "NodeTraversal" instead of "Node" to store the strand of nodes?

**Comment by josiahseaman** [comment]
Thank you @6br. Since the Django DB update has been merged now, it'll take some extra work to update this.  I'm glad you're using NodeTraversal.  That was the correct decision.  I recommend you bring the current master into your branch as resolve the conflicts there.

**Comment by josiahseaman** [comment]
I'm looking through the changes in this branch and I think it'll definitely depend on the changes I'm working on in i23_halpo_db.  The good news is I think we can get rid of Slices entirely.  The GFA tests are already passing in my branch.  Slices are still useful for test data, which I think we can replace with [Django Fixtures](https://django-testing-docs.readthedocs.io/en/latest/fixtures.html)  These can be saved as files and slightly separated from code.  They're also going to be more maintainable because it's just a saved database state.

How about I figure out how to handle the objects and you figure out what the core concept changed for directed DAGify LCS will be, then we'll followup the changes in i23_haplo_db?

**Pull request closed without merging**
